on: [push]

jobs:
  hercules-charts:
    runs-on: ubuntu-latest
    name: Hercules Git Insights
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Hercules
        uses: src-d/hercules@master
      - uses: actions/upload-artifact@master
        with:
          name: hercules_charts
          path: hercules_charts.tar
